// lib/leaderData.ts
import { Card } from '@/lib/types';

export const leaders: Card[] = [
  {
    title: 'வ.உ.சி (கப்பலோட்டிய தமிழன்)',
    description: 'வ.உ.சி இந்திய விடுதலைப் போராளி; நமது “கப்பலோட்டிய தமிழன்”. தூத்துக்குடி–கொழும்பு என்னும் இடங்களுக்கு சுதேசி கப்பல்களை இயக்கினார். தொழிலாளர் உரிமை, தேசிய சாமர்த்தியம் போன்றவற்றில் நீண்ட பங்களிப்பு செய்தவர். 1906-ல் கப்பல் நிறுவனத்தையும், 1908-ல் நூற்பாலை தொழிற்சாலை பணியாளர் வேலைநிறுத்தத்தையும் ஏற்படுத்தினார். அவர் வாழ்க்கை தியாகத்தால் மிகுந்தது.',
    image: require('@/assets/images/voc.jpg'),
    route: '/Sidebarsection/LeaderVOC',
    sectionKey: 'leader-voc',
    buttonLabel: 'View Details',
  },
  {
    title: 'பச்சையப்ப முதலியார்',
    description: 'கல்வி வளர்ச்சி மற்றும் அறநீதி பணிகளுக்கு சொத்து கொடுத்தவர். சென்னை பச்சையப்பா கல்லூரியை நிறுவினார். அந்தக் கால சிறந்த கல்வியாளர் மற்றும் அறக்கட்டளைத் தலைவர். அவர் வங்கிகள் திறக்கும் திட்டத்தையும் ஊக்குவித்தார். தமிழகம் முழுவதும் கல்விக்கு மட்டப்பிரதிபலனைக் கொண்டவர்களில் ஒருவர்.',
    image: require('@/assets/images/Pachaiyappa.jpg'),
    route: '/Sidebarsection/LeaderPachaiyappa',
    sectionKey: 'leader-pachaiyappa',
    buttonLabel: 'View Details',
  },
  {
    title: 'முத்துரங்க முதலியார்',
    description: 'முத்துரங்க முதலியார் கல்வி மற்றும் சமூகச் சேவையில் எளிதாக பங்களித்தவர். சிறிய கிராமங்களில் நூலகங்கள் அமைத்து, பயிற்சி வகுப்புகள் நடத்தினார். சமூக மாற்றங்களை வலுப்படுத்த தொடங்கிய முயற்சியாளர். வாழ்க்கையில் பொதுநல சேவை உண்மையாக அவர் மதித்த கொள்கை. அவரது சொர்க்கச் சேவைகள் இன்றும் வாழ்கின்றன.',
    image: require('@/assets/images/muthuranga.jpg'),
    route: '/Sidebarsection/LeaderMuthuranga',
    sectionKey: 'leader-muthuranga',
    buttonLabel: 'View Details',
  },
  {
    title: 'காலிங்கராய கவுண்டர்',
    description: 'காலிங்கராய கவுண்டர் இந்திய அரசியல் மற்றும் சமூக ஊழியத் துறையில் பெயிழ்ந்தவர். கிராமப் பிரச்னைகளை நாடி தீர்க்கும் நண்பராக இருந்தார். நீதி, சமத்துவம், கல்வி நிலைகளுக்கு ஊதியம் கொடுத்தார். பல தொண்டு அமைப்புகளை நடத்தினார். அவர் கடும் உறுதி கொண்ட சேவையாளர்.',
    image: require('@/assets/images/kalingaray.jpeg'),
    route: '/Sidebarsection/LeaderKalingaray',
    sectionKey: 'leader-kalingaray',
    buttonLabel: 'View Details',
  },
  {
    title: 'மருத நாயகம்',
    description: 'மருத நாயகம் தமிழ்நாட்டின் முன்னணி சாமூகவியலாளர் மற்றும் அரசியல் தலைவர். கிராம மக்களுக்கு அடிப்படை ஊழியங்களை ஏற்படுத்தி வாழ்வாதாரத்தை மேம்படுத்தினார். கல்வி வளர்ச்சி, சமூக நீதி ஆகியவற்றில் அசாதாரண பங்களிப்பு. மருத்துவ வசதிகள் இறைஞொகும்போது அவர் முதற்பங்கு வகித்தார். வாழ்க்கை ஒவ்வொரு சேவையாகவே இருந்தது.',
    image: require('@/assets/images/marudha.jpg'),
    route: '/Sidebarsection/LeaderMarudha',
    sectionKey: 'leader-marudha',
    buttonLabel: 'View Details',
  },
  {
    title: 'தீரன் சின்னமலை',
    description: 'தீரன் சின்னமலை இந்திய விடுதலைப் போராட்ட வீரர். மதுரை மத்திய சிறையில் அடக்கச் சிறையில் இருந்தவர். அசாதாரண வீரப்பாங்கு போது பிரபலமானார். அவரது பெயரில் எழுந்த பல கல்வி நிறுவனங்கள் காணப்படுகின்றன. சமூக சேவையில் நீண்ட காலம் ஈடுபட்டவர்.',
    image: require('@/assets/images/chinnamalai.jpeg'),
    route: '/Sidebarsection/LeaderChinnamalai',
    sectionKey: 'leader-chinnamalai',
    buttonLabel: 'View Details',
  },
  {
    title: 'நடேச முதலியார்',
    description: 'நடேச முதலியார் ஒரு வணிகவியலாளர் மற்றும் சமூக நலப்பணியாளர். கிராம மக்களுக்கு தொழில்முறைகளை விருத்தி செய்ய உதவினார். கல்வி, மருத்துவம் ஆகிய துறைகளில் பல அறக்கட்டளைகள் அமைத்தார். தொலைதூர ஆற்றல் திட்டங்களில் செயல்பட்டார். மக்கள் வாழ்வில் மாற்றம் கொண்ட வந்தவர்.',
    image: require('@/assets/images/natesa.png'),
    route: '/Sidebarsection/LeaderNatesa',
    sectionKey: 'leader-natesa',
    buttonLabel: 'View Details',
  },
  {
    title: 'ஆற்காடு சகோதரர்கள் இராமசாமி முதலியார்',
    description: 'தினசரியாக போதிக்கின்ற சகோதரர்கள்; அவர் ஆற்காடு கிராமத்தில் கல்வி வளர்ச்சிக்காக பாடசாலையைத் தொடங்கின. மக்களின் கல்வி மற்றும் சமூக வளங்களை மேம்படுத்த முயன்றனர். அறக்கட்டளை முயற்சிகளில் முன்முயற்சி எடுத்தனர். கிராம சமூகத்தில் மதிப்பு பெற்றவர்.',
    image: require('@/assets/images/arkadu.jpeg'),
    route: '/Sidebarsection/LeaderArkadu',
    sectionKey: 'leader-arkadu',
    buttonLabel: 'View Details',
  },
  {
    title: 'இலட்சுமணசாமி முதலியார்',
    description: 'இலட்சுமணசாமி முதலியார் விவசாய சமூகத்தில் முன்னிலை வகித்தவர். சிறு விவசாயிகளை ஒருங்கிணைத்து சமூக நலச் சேவைகளை மேற்கொண்டார். நிலரீதியாக மண் சீர்திருத்த நிகழ்ச்சிகளில் ஈடுபட்டார். கிராம வளர்ச்சிக்கு தன் வாழ்க்கையையும் அர்ப்பணித்தார். கல்வி மற்றும் மருத்துவ வசதி சிறப்பு அளித்தவர்.',
    image: require('@/assets/images/lakshmanasami.jpg'),
    route: '/Sidebarsection/LeaderLakshmanasami',
    sectionKey: 'leader-lakshmanasami',
    buttonLabel: 'View Details',
  },
  {
    title: 'திரு.வி.க',
    description: 'திரு.வி.க திராவிட முன்னேற்ற கழகம் (DMK) நிறுவிய தந்தை. தமிழர் உரிமை, கல்வி சமத்துவம், சமூக நலன் ஆகியவற்றுக்காக கடுமையாகப் போராடினார். “மண்ணும் மக்களும்” என்ற கொள்கையை எழுப்பினார். தமிழ் மொழி வளர்ச்சிக்கும் அவர் நிலைபாடு உறுதியாகும். அவர் மக்களின் மீதான குறை தீர்க்கும் போராட்ட தலைவராக இருந்தார்.',
    image: require('@/assets/images/thiru_v_k.jpg'),
    route: '/Sidebarsection/LeaderVK',
    sectionKey: 'leader-vk',
    buttonLabel: 'View Details',
  },
  {
    title: 'இராமலிங்கம் பிள்ளை',
    description: 'இராமலிங்கம் பிள்ளை கல்வி மற்றும் சமூக நிறுவனர். பெண்களின் கல்வியை ஊக்குவித்து பள்ளிகளைக் கொண்டு வந்தார். சமூக நீதி, வன்முறை எதிர்ப்புச் சக்தி ஆகியவற்றில் ஈடுபட்டார். கிராமப் பகுதியின் வாழ்க்கைக் நிலையை உயர்த்த அவரது திட்டங்கள் வாழ்கின்றன. தொண்டு செயல்முறையில் உயர்த்தப்பட்டார்.',
    image: require('@/assets/images/rams.png'),
    route: '/Sidebarsection/LeaderRamalingam',
    sectionKey: 'leader-ramalingam',
    buttonLabel: 'View Details',
  },
  {
    title: 'கி.ஆ.பே. விஸ்வநாதன்',
    description: 'கி.ஆ.பே. விஸ்வநாதன் ஒரு புகழ்பெற்ற கல்வியாளர் மற்றும் வரலாற்று ஆராய்ச்சியாளர். தமிழ் இலக்கிய வளர்ச்சித் துறையில் பல நூல்கள் எழுதியவர். கல்வித்துறையில் பெயர்பெற்ற கடமையில் இருந்தார். மாணவர்களில் ஆர்வத்தை ஊக்குவித்தார். தமிழ்த்தினத்தில் இன்றும் அவரின் பங்களிப்பு வாழுகின்றது.',
    image: require('@/assets/images/viswanathan.jpeg'),
    route: '/Sidebarsection/LeaderViswanathan',
    sectionKey: 'leader-viswanathan',
    buttonLabel: 'View Details',
  },
  {
    title: 'மு.வரதராஜன்',
    description: 'மு.வரதராஜன் சமூக சேவையாளர் மற்றும் கல்வித் தோற்றம் நடத்துனர். கிராமப் பகுதியில் பெண்கள் திறனை மேம்படுத்தும் வகுப்புகள் நடத்தினார். தொழில்முறை திறன்களை பயிற்சி செய்தார். சமூக நலனுக்காக பல திட்டங்களில் ஈடுபட்டார். அவரின் முயற்சிகள் பலரை ஊக்குவிக்கின்றன.',
    image: require('@/assets/images/varadarajan.jpeg'),
    route: '/Sidebarsection/LeaderVaradarajan',
    sectionKey: 'leader-varadarajan',
    buttonLabel: 'View Details',
  },
  {
    title: 'சிலம்பொலி செல்லப்பன்',
    description: 'சிலம்பொலி செல்லப்பன் தமிழ் சிறுவர் கல்வி வளர்ச்சிக்கு முக்கிய பங்காற்றினார். சிறுவர்களுக்காக பாடசாலைகள், விளையாட்டு மைதானங்கள் அமைத்தார். கலைவாசி, பாரம்பரியப் பண்புத்துண்டுகளை ஊக்குவித்தார். சமூகத்தை ஒருமையாக்க அவர் பணிசெய்தார். அவரது பணிகள் இன்றும் ஓவியமாகி இருக்கின்றன.',
    image: require('@/assets/images/silamboli.png'),
    route: '/Sidebarsection/LeaderSilamboli',
    sectionKey: 'leader-silamboli',
    buttonLabel: 'View Details',
  },
  {
    title: 'கலைவாணர் என்.எஸ். கிருஷ்ணன்',
    description: 'கலைவாணர் என்.எஸ். கிருஷ்ணன் தமிழ் கர்நாடக இசை மற்றும் சினிமா துறையில் பெயற்சென்றவர். பல இசை நிகழ்ச்சிகள், திரைப்பட இசைகள் மூலம் பிரபலம் அடைந்தார். இருக்கும் இசைத்திறனைக் கொண்டு சமூக விழிப்புணர்வு செய்யும் பணியிலும் ஈடுபட்டார். தமிழ்த் கலையை உலகளவில் பரப்பினார்.',
    image: require('@/assets/images/NSK.png'),
    route: '/Sidebarsection/LeaderKrishnan',
    sectionKey: 'leader-krishnan',
    buttonLabel: 'View Details',
  },
  {
    title: 'பொள்ளாச்சி மகாலிங்கம்',
    description: 'பொள்ளாச்சி மகாலிங்கம் விவசாய நெறி மேம்பாட்டில் பெயர்பெற்றவர். தற்சமூக சேவைகளிலும் காவியமான பங்களிப்பு. விவசாயிகள் நலன் மற்றும் நீதி ஆகியவற்றுக்கு உறுதியாக சேவை செய்தார். கிராம வளர்ச்சிக்கு இயந்திர வசதிகள் கொண்டு வந்தார். மாற்றத்தின் தூணாக இருந்தவர்.',
    image: require('@/assets/images/pollachi.jpg'),
    route: '/Sidebarsection/LeaderPollachi',
    sectionKey: 'leader-pollachi',
    buttonLabel: 'View Details',
  },
  {
    title: 'கோவை செழியன்',
    description: 'கோவை செழியன் தொழில் மற்றும் சமூக சேவைத் தலைமை. கோவை நகரின் தொழில் வளர்ச்சியில் முக்கிய பங்காற்றினார். ஏர்வட்டி வழித்தட திட்டங்களில் பங்கு பெற்றார். கல்வி அறக்கட்டளை நிர்வாகத்தில் ஈடுபட்டார். கோவை மேம்பாட்டுக்கு அவர் வழிகாட்டியவர்.',
    image: require('@/assets/images/coimbatore.webp'),
    route: '/Sidebarsection/LeaderCoimbatore',
    sectionKey: 'leader-coimbatore',
    buttonLabel: 'View Details',
  },
  {
    title: 'நாவலர் நெடுஞ்செழியன்',
    description: 'நாவலர் நெடுஞ்செழியன் தமிழ்ப்புத்தக எழுத்தாளர் மற்றும் சமூக விமர்சகர். சமூக மாற்றங்களை எழுத்தால் ஊக்குவித்தார். பல சிறப்புப் புனைகதைகள், கட்டுரை நூல்கள் எழுதியவர். கல்வி குறித்து தெரிந்து கொள்வதற்கு நூலகப் பணியில் ஈடுபட்டார். தமிழ் இலக்கியத்தில் அவரின் பங்களிப்பு குறிப்பிடத்தக்கது.',
    image: require('@/assets/images/nedu.jpg'),
    route: '/Sidebarsection/LeaderNedunchezhiyan',
    sectionKey: 'leader-nedunchezhiyan',
    buttonLabel: 'View Details',
  },
  {
    title: 'பேரா.க.அன்பழக',
    description: 'பேரா.க.அன்பழக அரசியல் தமிழர் மற்றும் சமூக சேவையாளர். சமூக நீதி, கல்வி சமத்துவம் ஆகியவற்றில் நீண்ட கால பங்களிப்பு. கிராமப்புற பிரச்சனைகள் தீர்க்க முதல்வியாயிருந்தார். மக்களுடன் நெருங்கிப் பழகினவர். அவரின் பாசமான சேவை நினைவில் உள்ளது.',
    image: require('@/assets/images/anbalagan.jpg'),
    route: '/Sidebarsection/LeaderAnbalagan',
    sectionKey: 'leader-anbalagan',
    buttonLabel: 'View Details',
  },
];
