export const locationMasterData = [
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'Eral', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'Sattankulam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'Tiruchendur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'Srivaikundam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tirunelveli', taluk: 'Ambasamudram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tirunelveli', taluk: 'Cheramadevi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tirunelveli', taluk: 'Nanguneri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tirunelveli', taluk: 'Radhapuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Kanyakumari', taluk: 'Thiruvattur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Kanyakumari', taluk: 'Killiyur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Kanyakumari', taluk: 'Agasthisvaram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Kanyakumari', taluk: 'Thovalai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Kanyakumari', taluk: 'Vilavankodu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Kanyakumari', taluk: 'kalkulam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tenkasi', taluk: 'Sankarankovil', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tenkasi', taluk: 'Sivagiri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tenkasi', taluk: 'Thiruvengadam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tenkasi', taluk: 'Alangkulam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tenkasi', taluk: 'Tenkasi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tenkasi', taluk: 'Kadayanallur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tenkasi', taluk: 'Senkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tenkasi', taluk: 'V.K.Pudur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'Ettayapuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'Kayatharu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'kovilpatti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'Ottapidaram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'Vilathikulam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tottukkudi', taluk: 'thootukkudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tirunelveli', taluk: 'Tisaiyan vilai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tirunelveli', taluk: 'Manur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tirunelveli', taluk: 'Palayamkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Nanchil Mandalam', district: 'Tirunelveli', taluk: 'Tirunelveli', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chengalpattu', taluk: 'Chengalpattu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chengalpattu', taluk: 'Thirukkalukundram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chengalpattu', taluk: 'Vandalur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chengalpattu', taluk: 'Thirupporur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chengalpattu', taluk: 'Cheyyur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chengalpattu', taluk: 'Madhurantakam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chengalpattu', taluk: 'Pallavaram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chengalpattu', taluk: 'Tambaram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Ambattur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Aminjikarai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Ayanavaram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Egmore', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Maduravoyal', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Mambalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Perambur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Pursawalkam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Thiruvottiyur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Tondiarpet', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Alandur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Guindy', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Mylapore', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Sholinganallur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Chennai', taluk: 'Velachery', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Bhuvanagiri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Chidambaram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Kattumannarkoil', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Srimushnam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Cuddalore', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Kurinjipadi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Panruti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Titagudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Veppur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Cuddalore', taluk: 'Vridhachalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kanchipuram', taluk: 'Kanchipuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kanchipuram', taluk: 'Uttaramerur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kanchipuram', taluk: 'Walajabad', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kanchipuram', taluk: 'Kunrathur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kanchipuram', taluk: 'Sriperumpudur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Ranipettai', taluk: 'Arakonam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Ranipettai', taluk: 'Arcot', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Ranipettai', taluk: 'Walajapettai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Ranipettai', taluk: 'Sholingur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Ranipettai', taluk: 'Nemili', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Ranipettai', taluk: 'Kalavai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruppattur', taluk: 'Thiruppattur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruppattur', taluk: 'Ambur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruppattur', taluk: 'Natrampalli', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruppattur', taluk: 'Vaniyampadi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'Thiruvallur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'Ponneri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'Gummudipundi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'Avadi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'Pondamalli', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'Tiruttani', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'Pallipattu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'Uttukkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvallur', taluk: 'R.K.Pettai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Arani', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Tandarampattu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Kalasappakkam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Polur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Jamaunamarudhur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Cheyar', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'wandavasi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Vempakkam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Thiruvannamalai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Kilpennathur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Chetpet', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Thiruvannamalai', taluk: 'Chengam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Vellore', taluk: 'Gudiyattam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Vellore', taluk: 'Vellore', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Vellore', taluk: 'K.V.Kuppam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Vellore', taluk: 'Katpadi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Vellore', taluk: 'Anaikattu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Vellore', taluk: 'Peranampattu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Gingee', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Marakkanam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Melmalaiyanur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Tindivanam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Kandachipuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Vanur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Vikkiravandi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Thiruvennainallur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Villupuram', taluk: 'Vilupuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kallakurichi', taluk: 'Kallakurichi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kallakurichi', taluk: 'Chinna Salem', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kallakurichi', taluk: 'Sankarapuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kallakurichi', taluk: 'Thirukkovilur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kallakurichi', taluk: 'Kalrayan hills', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kallakurichi', taluk: 'Vanapuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Tondai mandalam', district: 'Kallakurichi', taluk: 'Ulundurpettai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Ariyalur', taluk: 'Ariyalur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Ariyalur', taluk: 'Sendurai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Ariyalur', taluk: 'Udaiyarpalayam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Ariyalur', taluk: 'Andimadam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Mayiladuthurai', taluk: 'Kuttalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Mayiladuthurai', taluk: 'Mayiladuthurai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Mayiladuthurai', taluk: 'Tarankampadi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Mayiladuthurai', taluk: 'Sirkazi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Nagappattinam', taluk: 'Nagappattinam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Nagappattinam', taluk: 'Kilvelur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Nagappattinam', taluk: 'Thirukkuvalai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Nagappattinam', taluk: 'Vedaranyam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Perambalur', taluk: 'Perambalur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Perambalur', taluk: 'Alathur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Perambalur', taluk: 'Kunnam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Perambalur', taluk: 'Veppamtattai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Pudukkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Illupur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Manamelkudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Kulattur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Avudaiyarkovil', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Ponnamaravathi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Aranthanki', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Karampakkudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Kandarvakkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Viralimalai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Pudukkottai', taluk: 'Alankudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Thanjavur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Kumbakonam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Pattukkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Papanasam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Thiruvidaimarudur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Peravurani', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Thiruvonam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Budhalur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Thiruvaiyaru', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thanjavur', taluk: 'Orathanadu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Lalkudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Manachanallur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Thiruverumpur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Musiri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Thottiyam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Manapparai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Thuraiyur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Marungapuri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Srirangam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Thiruchirappalli East', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Tiruchirappalli', taluk: 'Thiruchirappalli West', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Thiruvarur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Koothanallur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Needamangalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Mannarkudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Kudavasal', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Nannilam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Thiruthuraipundi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Valankaiman', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Cholamandalam', district: 'Thiruvarur', taluk: 'Muthupettai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Madurai East', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Madurai West', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Madurai North', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Madurai South', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Vadipatti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Kallikudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Melur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Tirupparankunram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Thirumangalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Peraiyur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Madurai', taluk: 'Usilampatti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Ramanathapuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Rajasingamangalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Kilakkarai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Rameswaram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Kadaladi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Kamudhi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Mudukulattur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Paramakudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Ramanathapuram', taluk: 'Thiruvadanai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Devakottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Karaikkudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Sivagangai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Singampuneri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Thiruppattur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Ilayankudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Kalaiyarkovil', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Manamadurai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivagangai', taluk: 'Thirubhuvanam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Theni', taluk: 'Theni', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Periyakulam', taluk: 'Periyakulam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Bodinayakkanur', taluk: 'Bodinayakkanur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Uttamapalayam', taluk: 'Uttamapalayam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Andipatti', taluk: 'Andipatti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Virudhunagar', taluk: 'Virudhunagar', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Aruppukkottai', taluk: 'Aruppukkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Kariyapatti', taluk: 'Kariyapatti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Thiruchuli', taluk: 'Thiruchuli', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sattur', taluk: 'Sattur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Vempakkottai', taluk: 'Vempakkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Rajapalayam', taluk: 'Rajapalayam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Sivakasi', taluk: 'Sivakasi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Srivilliputhur', taluk: 'Srivilliputhur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Pandya mandalam', district: 'Watrap', taluk: 'Watrap', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Kovai North', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Kovai South', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Annur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Mettupalayam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Pollachi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Sulur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Perur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Anaimalai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Kinattukadavu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Coimbatore', taluk: 'Valparai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dharmapuri', taluk: 'Dharmapuri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dharmapuri', taluk: 'Karimangalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dharmapuri', taluk: 'Nallampalli', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dharmapuri', taluk: 'Palakodu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dharmapuri', taluk: 'Pennakaram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dharmapuri', taluk: 'Harur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dharmapuri', taluk: 'Pappireddipatti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Dindugal East', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Dindugal West', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Natham', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Nilakkottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Kodaikanal', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Kujiliyamparai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Ottanchattiram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Palani', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Vedachandur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Dindugal', taluk: 'Attur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Erode', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'bhavani', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Gobichettipalayam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Sathyamangalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Kodumudi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Modakurichi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Perunthurai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Anthiyur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Nambiyur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Erode', taluk: 'Talavadi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Karur', taluk: 'Karur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Karur', taluk: 'Aravakurichi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Karur', taluk: 'Kulittalai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Karur', taluk: 'Manmangalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Karur', taluk: 'Pugalur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Karur', taluk: 'Kadavur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Karur', taluk: 'Krishnarayapuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Krishnagiri', taluk: 'Krishnagiri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Krishnagiri', taluk: 'Hosur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Krishnagiri', taluk: 'Anchetti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Krishnagiri', taluk: 'Tenkanikottai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Krishnagiri', taluk: 'Culagiri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Krishnagiri', taluk: 'Bargur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Krishnagiri', taluk: 'Pochampalli', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Krishnagiri', taluk: 'Uttankarai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Namakkal', taluk: 'Namakkal', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Namakkal', taluk: 'Kolli hills', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Namakkal', taluk: 'Moganur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Namakkal', taluk: 'Kumarapalayam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Namakkal', taluk: 'Rasipuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Namakkal', taluk: 'Sendamangalam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Namakkal', taluk: 'Paramathivelur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Namakkal', taluk: 'Thiruchenkodu', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Nilgiris', taluk: 'Coonur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Nilgiris', taluk: 'Kottagiri', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Nilgiris', taluk: 'Gudalur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Nilgiris', taluk: 'Pandalur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Nilgiris', taluk: 'Udagai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Nilgiris', taluk: 'Kundah', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Salem', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Salem South', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Salem West', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Gangavalli', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Attur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Pettanaikkan palayam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Talavasal', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Kadayampatti', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Mettur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Omalur', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Valapadi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Yercaud', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Edappadi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Salem', taluk: 'Sankari', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Tiruppur North', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Tiruppur South', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Avinashi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Dharapuram', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Kangeyam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Palladam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Udumalaipettai', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Uttukuzi', village: ' ' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kongalnagaram' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Pudupalayam' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Pannaikinar' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Mukkudu-Jallipatti' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Myvadi' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Jothampatti' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kadathur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Sholamadevi' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Thungavi' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Vanjiyapudur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Singalandapuram' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kulanaickanpatti' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Madathukulam (Part)' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Sedamangalam' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Karattumadam' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Periyapappanuthu' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kaniyur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Madappur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kodangipatti' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Mavuttampatti' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Pollikalipalayam' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Valayapalayam' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kannamanaickanur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Thennampalayam' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Sarkaraipattipudur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kallapuram' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Poolavadi' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Thimmankuthu' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kaniyur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Kollankoil' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Nagalur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Valayapalayam' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Udumalpet' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Elayamuthur' },
  { state: 'தமிழ்நாடு', mandalam: 'Kongumandalam', district: 'Tiruppur', taluk: 'Madathukulam', village: 'Pudupalayam' },
];
